// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwtfrcvmzsyzcebeueoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3dGZyY3ZtenN5emNlYmV1ZW9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MzgwMDksImV4cCI6MjA2MDExNDAwOX0.6Zn1oss0abzT4is5KeJI6N9pr8FoyKz3_uKDAB1cqWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);